"""
Authors: Chase and Ian
Purpose: Run word2vec on the random walks generated by walking-rdf-and-owl
Input: 	path to walk file
		output file name
Output: 
Sample Call:
"""


# import modules & set up logging
from gensim.models import Word2Vec
import logging
from sys import argv

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)



class MySentences(object):
    def __init__(self, filename):
        self.filename = filename

    def __iter__(self):
        for line in open(self.filename, 'r'):
            yield line.split()


if __name__ == "__main__":            
	input_file = argv[1] #'experiments/aug13/walklist_stratified.out'
	sentences = MySentences(input_file)

	model = Word2Vec(sentences, min_count= 0, size = 256, sg = 1, window = 5, workers = 48, iter=15, compute_loss=True)
	model.wv.save_word2vec_format(argv[2])
